name: example
description: "Example for Chatnels Widget."
version: 0.2.0
publish_to: 'none'

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  chatnels_widget:
    path: ../
  cupertino_icons: ^1.0.2
  webview_flutter: ^4.4.4
  webview_flutter_android: ^3.15.0
  webview_flutter_wkwebview: ^3.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
