publish_to: none

name: chatnels_widget
description: "A Flutter plugin that allows you to integrate Chatnels"
version: 0.1.0
# authors: Justin Lee <justin.lee@chatnels.com>
homepage: https://www.chatnels.com
repository: https://github.com/Chatnels/chatnels-widget-flutter.git

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
